name: Publish EPUB

on:
  push:
    branches:
      - main


jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pandoc & co
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
    - name: Generate EPUB
      run: make epub
    - name: Generate PDF
      run: make pdf
    - uses: actions/upload-artifact@v3
      with:
        name: generated-files
        path: |
          uncurled.epub
          uncurled.pdf
